### ISSUE TITLE
Should show and filter against farm free IPs 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#102]
![image](https://user-images.githubusercontent.com/64129/145992159-2024e144-e6f9-48e9-a972-e9784dcf4bc0.png)
and while we are at it, let's remove created column too.

**Comment by RafyAmgadBenjamin** [comment]
I have shown free public IPs, total and Used in this issue
https://github.com/threefoldtech/tfchain_explorer/issues/93

so shall  i keep what i have done in the previous issue or just follow this issue ?

**Comment by RafyAmgadBenjamin** [comment]
After discussion with @rkhamis, we decided to keep the free, total, used public IPs and remove the created column

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_fix_issues`
### Commit
65c1429b3754b8e583f5be23953fb0a63f17da5a
![image](https://user-images.githubusercontent.com/46320202/146001234-82d5260d-9ec8-4491-b739-7235daec51ce.png)

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`

- farms page
![image](https://user-images.githubusercontent.com/46320202/147670600-957f0897-bf50-4166-8f5d-eefdbfc63497.png)
