### ISSUE TITLE
Auto sort by ID as default (nodes, and farms)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#103]
![image](https://user-images.githubusercontent.com/64129/145992745-99d66cff-e2a2-4df7-980a-d51e76e779eb.png)

this is how it looks like right now on the default view, while farms seem to be sorted just fine 
![image](https://user-images.githubusercontent.com/64129/145992861-7c73242c-6b91-4228-8826-081538b21fa3.png)

**Comment by RafyAmgadBenjamin** [comment]
This is a duplicate from this issue
https://github.com/threefoldtech/tfchain_explorer/issues/97
