### ISSUE TITLE
Nodes view should show online ones by default

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#104]
![image](https://user-images.githubusercontent.com/64129/145993131-ee1c609a-95e9-446d-84cc-e56d7da3f91a.png)

by default it's showing offline nodes, expected behavior i showing online nodes by default.

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master`
![image](https://user-images.githubusercontent.com/46320202/146003304-89894ea3-98ed-4d12-a335-71b8bb467ff4.png)

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`

![image](https://user-images.githubusercontent.com/46320202/147670475-fb9e7ebf-1d51-4656-bb50-f1b9305662be.png)
