### ISSUE TITLE
Public IP Filters

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/tfchain_explorer#107]
In node/farm views

Filtering of public IPs should work against free public IPs.
rename the filter to "free public IP"

**Comment by RafyAmgadBenjamin** [comment]
The part related to the node is done 
046213192faafedda222fceb5505603066a89ecb
still need to work on the farm part

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch 
`master_fix_issues`
### Commit 
1d52784438470f60cef014faae1bf8211f0a17c0

![image](https://user-images.githubusercontent.com/46320202/146342605-76c43123-ecba-435d-8576-20852b490bd0.png)

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`
- In nodes page
![image](https://user-images.githubusercontent.com/46320202/147669862-421918ed-7a2f-4207-816a-197be6fe3fc3.png)


- In Farms Page
![image](https://user-images.githubusercontent.com/46320202/147669783-9bdcbfcc-6715-4667-b237-cf55f61a39f7.png)
