### ISSUE TITLE
Confusing filters values

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/tfchain_explorer#115]
## Description
When I try to move the filter, I found values like 200 where the slider must be from 1 to 10 TB
I know that it is a fraction of 1 (almost 200 GB) but it seems confusing and not clear.

## Screenshot
![image](https://user-images.githubusercontent.com/11272864/147093635-d6f4374c-6bf3-477e-be7c-a874e9e5bc67.png)

## Suggestions
1. Add a unit after min value as max value and handle it according to the value
2. Make step only one ( We can't search for values less than 1 TB or whatever the unit)
3. Allow values to be float/double and let the unit fixed

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/116

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`

![image](https://user-images.githubusercontent.com/46320202/147668383-5e4459a2-c072-45fc-ba78-5e07eb9bbc67.png)
