### ISSUE TITLE
Filter ranges should include all nodes

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_explorer#121]
Currently, the maximum CRU in the filter section defaults to 60. This does not include nodes that have 64 cores, which can only be seen by disabling the CRU filter. Likewise, HRU defaults to 300 and limits displayed nodes in the same way.

**Issue**
Overriding the maximum filter value does not change the actual range of the slider or the nodes that are displayed.

**Suggestion**
The maximum value could be derived from the max present in available data, thus displaying all nodes by default. For example, when the node with the most cores has CRU 64, the maximum filter value would be set for 64.

**Comment by xmonader** [comment]
we will go with manually updating the max to 64 cores for CPU and 1000 TB for HDD

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
`master_fix_range_filter`
### Commit 
f3553c5e5f9573ad90dcd32b16c41d8123eaad4a
![image](https://user-images.githubusercontent.com/46320202/147655189-1edce877-2f65-43f6-8a7c-89805efb1401.png)

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`

**Comment by RafyAmgadBenjamin** [comment]
I have opened a feature request by this 
https://github.com/threefoldtech/tfchain_explorer/issues/127

**Comment by scottyeager** [comment]
Thanks @xmonader and @RafyAmgadBenjamin

**Comment by sabrinasadik** [comment]
64 does not seem to be enough. Currently talking to a farmer who has a node with 96 cores. Let's raise to 256 if there are no objections?

**Comment by RafyAmgadBenjamin** [comment]
Per @xmonader request we will triple the number of the core for now then we can add all the suggestions related to the `tfchain_explorer` as feature requests 

## Done 
### Branch
`master_filters_max`
### PR
https://github.com/threefoldtech/tfchain_explorer/pull/170

**Comment by RafyAmgadBenjamin** [comment]
i will close this issue and opened a feature request which is in the project 
https://github.com/threefoldtech/tfchain_explorer/issues/127  in project `3.0.1`
