### ISSUE TITLE
Pricing policy filter

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#125]
According to test case [TC234](https://app.testlodge.com/a/26076/projects/40893/suites/193853?expand_section=305792#case_3354997), there must be an option in the Explorer to allow filtering by pricing policy.

**Comment by MohamedElmdary** [comment]
### Added

#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/137
