### ISSUE TITLE
create a new workflow to build/push docker image

### ISSUE THREAD

**Issue by abom** [threefoldtech/tfchain_explorer#133]
also, it's better to use `appVersion` in chart.yaml, `version` is used to track chart changes, not app changes.

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
`master_github_actions`

**Comment by RafyAmgadBenjamin** [comment]
### Verified 

![image](https://user-images.githubusercontent.com/46320202/155342971-7f0a02f6-46de-4642-b194-b0585bacaaf6.png)
