### ISSUE TITLE
Mainnet explorer points to devnet proxy

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_explorer#134]
See discussion here: https://github.com/threefoldtech/tf_operations/issues/544

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/tfchain_explorer/commit/15bb0d18f6f262eb03ce7662d8380b294d005739

rc19 is already out

**Comment by scottyeager** [comment]
Thanks Thabet.
