### ISSUE TITLE
Add a warning that node statusses are fetched every 2 hours

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_explorer#141]
To not overload the blockchain we decided to push uptime reports every 2 hours. This means a node can go down but still show as up unless 2 hours have passed. We need to indicate on the page that we only fetch the node status every 2 hours

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch 
`master_warnings`

![image](https://user-images.githubusercontent.com/46320202/151979804-f64e8891-bced-472c-9e7a-1cf87ae66130.png)
