### ISSUE TITLE
Improve queries to graphql

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfchain_explorer#147]
Currently, explorer creates one huge query against graphql that causes graphql to be very slow. It's better to create many smaller queries and leverage on server side aggregation (like counting nodes)

For example: Nodes and farms must be paginated. It means you fetch pages of nodes (let's say 20) and then on loading next page you fetch the next 20. and so on. 

Counting of nodes and other objects must be done on server side.

**Comment by abom** [comment]
@AhmedHanafy725 @OmarElawady please open other issues in https://github.com/threefoldtech/grid3_client_ts and https://github.com/threefoldtech/terraform-provider-grid

**Comment by waleedhammam** [comment]
gridproxy issue: https://github.com/threefoldtech/tfgridclient_proxy/issues/82

**Comment by RafyAmgadBenjamin** [comment]
#### Done 
#### Branch 
`master_use_api_pagination`
#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/148

**Comment by RafyAmgadBenjamin** [comment]
![image](https://user-images.githubusercontent.com/46320202/151958052-e0220046-2256-453b-bed4-275a4cd33d3f.png)

old:
1.6 MB = 6 ~ 8 sec
new:
40 KB / chunk = 1 ~ 2 sec

**Comment by RafyAmgadBenjamin** [comment]
### Verified on 
https://explorer.dev.grid.tf/

![image](https://user-images.githubusercontent.com/46320202/155511581-db835d19-5c19-47a8-977d-2d78bfbd0571.png)
