### ISSUE TITLE
On helm deployment remove default dashboard.com ingress

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_explorer#159]
When deploying the explorer via helm we don't define an ingress, since there is already one configured. There is always a dashboard.com ingress created. Could this be disabled? Or is there another way to disable on each deployment/upgrade?

![image](https://user-images.githubusercontent.com/88312671/154029194-9e4f33b2-d20d-4265-91f2-253396259877.png)

**Comment by RafyAmgadBenjamin** [comment]
sorry, I don't understand what you mean exactly,
do you want to remove the default value for the domain in ingress ? or do you want to stop ingress itself in the helm chart ???

**Comment by coesensbert** [comment]
I think removing ingress from the helm chart will be the quickest fix. It's just a minor annoyance now since we don't define an ingress when deploying / upgrading the explorer, but a _dashboard.com_ ingress is created every time.

**Comment by RafyAmgadBenjamin** [comment]
###  Done 
### Branch 
`master_disable_ingress`

**Comment by RafyAmgadBenjamin** [comment]
After more discussion, we decided to keep ingress enabled and as you handle this with external ingress you can disable helm ingress bypassing to is `--set.ingress.enabled=false`

**Comment by coesensbert** [comment]
Aha that is also good! Did not know. Will test with next release. Thx!
