### ISSUE TITLE
Node missing from explorer

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_explorer#160]
A farmer reports that they're unable to see their node (511) in v3 explorer, either as online or offline. This node appears in graphql and can also be queried via gridproxy.

**Comment by RafyAmgadBenjamin** [comment]
we have checked the explorer on mainnet and the desired node (511) is there

![image](https://user-images.githubusercontent.com/46320202/155480079-de0021f8-2b03-4944-8900-03cec6a13546.png)
![image](https://user-images.githubusercontent.com/46320202/155480138-4e564e40-f914-42b8-8542-e924b8fd3976.png)

so it is not reproducible and actually, we can't find this node in graphql either in devnet or testnet so it must be mainnet and actually, it is listed in the explorer as mentioned before
