### ISSUE TITLE
Failed to fetch node resources info.

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_explorer#161]
Opening node details for node 582, produces error: `Failed to fetch node resources info.` Farmer is also confused because this node shows only when the online toggle is not selected, but still shows online on the details page:

![image](https://user-images.githubusercontent.com/17682591/154584249-6f7e9dc3-75c1-482b-8d69-2a14607bfe6e.png)

![image](https://user-images.githubusercontent.com/17682591/154584187-7bc504e2-79c3-4359-8d51-77a817cb8145.png)

Gridproxy produces errors when attempting to query this node:
```
https://gridproxy.grid.tf/nodes/582
{"Error":"Bad Gateway","Message":"error fetching node version: context deadline exceeded: bad gateway"}

https://gridproxy.grid.tf/nodes/582/status
{"Error":"Internal Server Error","Message":"failed get key GRID3NODE:582 : redigo: nil returned"}
```

**Comment by coesensbert** [comment]
I'm guessing this has to do with the current yggdrasil issues we have on the gridproxy's

**Comment by RafyAmgadBenjamin** [comment]
sometimes, gird proxy didn't give us a response with data (or grid proxy respond with bad gateways)

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch 
`master_gridProxy_updates`
### Commit
ee42c744112c97be5bd0ae0ce86d8e7d69e37cf2

**Comment by RafyAmgadBenjamin** [comment]
the used resources and total resources used to be under capacity attribute in the object but object  attributes was changed and it is no longer under capacity, it is now under the object directly

**Comment by RafyAmgadBenjamin** [comment]
### Verified on 
[`explorer.dev.grid.tf`
](https://explorer.dev.grid.tf/nodes)


![image](https://user-images.githubusercontent.com/46320202/155344480-a57115cf-c6c3-41b9-9bb1-8f49d69202c3.png)
