### ISSUE TITLE
v3.0.0-rc28: No Farms and Public IPs listed on Statistics page

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_explorer#167]
Seen this on all explorers: dev, test & mainnet

**Comment by coesensbert** [comment]
![image](https://user-images.githubusercontent.com/88312671/155302781-5484f976-d168-43fb-908c-a10ef84ed3e9.png)

**Comment by RafyAmgadBenjamin** [comment]
@OmarElawady, can you expose this data through APIs in the grid proxy, so when we move to grid proxy instead of graphql, we can render this data easily

**Comment by OmarElawady** [comment]
They are already exposed on https://gridproxy.dev.grid.tf/stats

**Comment by RafyAmgadBenjamin** [comment]
Thank @OmarElawady, once we moved to `gridproxy`, we will render them

**Comment by sabrinasadik** [comment]
Still showing 0 farms and 0 ip's - any status update? Does not look good to users now.

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch 
`master_statistics_gridproxy`

![image](https://user-images.githubusercontent.com/46320202/158187150-9c7743d0-09cc-4c8d-9930-6abca92f6e8e.png)
