### ISSUE TITLE
Hovering over icons on the let menu should show name of the section

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#177]
Right now it doesn't show what those sections are unless you open the hamburger menu on the top left
![Screenshot 2022-03-08 at 16 23 00](https://user-images.githubusercontent.com/31733464/157268688-f03f75b5-0a9e-4565-8f6c-3fdd0c117c7b.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch 
`master_fix_bugs`

![Screenshot from 2022-03-14 12-45-11](https://user-images.githubusercontent.com/46320202/158160169-c2cc3d78-b3eb-48b6-9ec4-487a0f9fe393.png)
![Screenshot from 2022-03-14 12-45-07](https://user-images.githubusercontent.com/46320202/158160177-09a58f0d-7231-4a15-b15a-f2f40a462484.png)
![Screenshot from 2022-03-14 12-44-45](https://user-images.githubusercontent.com/46320202/158160189-6b3fe523-63e3-4974-9fc2-9658707fffa9.png)
