### ISSUE TITLE
Change filters to dropdown

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#180]
Changing filters to a dropdown menu will give the explorer a more structured and clean look. Next to the dropdown we can add a text field to filter.

**Comment by RafyAmgadBenjamin** [comment]
can you explain more about this or show examples of how do you want this to be done?

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/194
