### ISSUE TITLE
Change color of DIY certification label

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#181]
Red color makes it seem as if the farm is offline. Is a color even needed? If yes, pls change to a more neutral color.

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch 
`master_fix_bugs`

![image](https://user-images.githubusercontent.com/46320202/158142058-192a83ff-acf6-4b0e-996d-54294274765d.png)
