### ISSUE TITLE
Hide uptime if node is down

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#182]
Right now, offline nodes still show an uptime which is confusing. Uptime should be hidden for nodes that are down.

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch 
`master_fix_bugs`

![image](https://user-images.githubusercontent.com/46320202/158154726-3e762fe2-b812-45c7-a90a-70f1f18e332c.png)
![image](https://user-images.githubusercontent.com/46320202/158154791-763cbbff-a658-486e-9a88-9215a7129036.png)
