### ISSUE TITLE
Move world map under statistics

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#183]
I think it would make more sense to add the map to the statistics tab since we want to show where our nodes are located (stats)

**Comment by RafyAmgadBenjamin** [comment]
- I totally understand your point but we were asked before to allow the filtering of the nodes to be reflected on the map 
https://github.com/threefoldtech/tfchain_explorer/issues/79

so if we moved the map to the statistics page, we will lose these features

**Comment by sabrinasadik** [comment]
Fair enough!
