### ISSUE TITLE
Typo under node tab

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#184]
Right now it says 

'Nodes status are updated every 2 hours.'

Please change to

'Node statuses are updated every 2 hours'

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_fix_bugs`
![image](https://user-images.githubusercontent.com/46320202/158137422-3be65b0e-399e-4e6c-8454-255f0fcde4e4.png)
