### ISSUE TITLE
Statistics: icons too big

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#185]
In order for us to fir the world map on the page as well, icons need to be a lot smaller - less than half of what they are is enough I think

**Comment by mohamedamer453** [comment]
verified on https://explorer.dev.grid.tf/

The icons are much smaller now and the world map fits in the page and only the lower half of the map is not visible and needs to be scrolled to.

### Old

![image](https://user-images.githubusercontent.com/101194226/163142091-e389c416-5ddb-4a22-bf0e-96d383d3ce14.png)

### New

![image](https://user-images.githubusercontent.com/101194226/163142192-85a135dd-0cf5-4acb-81b1-517aa1813a7c.png)
