### ISSUE TITLE
Explorer v3 not working

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#189]
Explorer V3 keeps loading: https://explorerv3.grid.tf/

**Comment by RafyAmgadBenjamin** [comment]
It is working now 
![image](https://user-images.githubusercontent.com/46320202/159232229-f0801401-1ec7-40ce-b940-5ab5a1131044.png)
![image](https://user-images.githubusercontent.com/46320202/159232243-6a500d6a-fa53-4795-a7b9-157fa3656517.png)
![image](https://user-images.githubusercontent.com/46320202/159232256-5da53ce0-eb47-46ad-81ee-542ba484c1a2.png)
