### ISSUE TITLE
Add a loader on the nodes table

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_explorer#190]
Would be better to add an indication of the nodes table that the data is loading. Currently it takes a few seconds and then all of sudden the table is populated.

**Comment by mohamedamer453** [comment]
verified on https://explorer.dev.grid.tf

A loading bar appears briefly when the data in the table is still loading.


![Screenshot from 2022-04-13 11-15-422](https://user-images.githubusercontent.com/101194226/163143775-6954fb2f-5164-4005-aba5-7b2d73740621.png)
