### ISSUE TITLE
DIY label is not correct

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#191]
Titans are still being marked as DIY instead of certified on explorer V3. Graphql says otherwise, after running the certification script (see https://github.com/threefoldtech/tf_operations/issues/752)

**Comment by asamirr** [comment]
You mean the farms in https://explorer.dev.grid.tf/farms ?

**Comment by sabrinasadik** [comment]
Yes

**Comment by asamirr** [comment]
I just checked https://graphql.grid.tf/graphql and when I ran the following query `query MyQuery {
  farms {
    name
    certificationType
  }
}
` found that all of them were DIY

**Comment by sabrinasadik** [comment]
My bad, I mean the nodes. Long day, apologies

**Comment by MohamedElmdary** [comment]
@sabrinasadik I think its working as expected
![image](https://user-images.githubusercontent.com/31689104/160642930-cb58cb1e-4636-4a21-ac50-63ac004cf306.png)

**Comment by sabrinasadik** [comment]
![photo_2022-03-29 17 07 45](https://user-images.githubusercontent.com/31733464/160643791-9300ffda-2faf-4b3f-9a24-5d9b15ec799d.jpeg)

**Comment by sabrinasadik** [comment]
Shouldn't only nodes get a certification label? The farm shows DIY but the node certified? @rkhamis

**Comment by sabrinasadik** [comment]
Need to hide farm certification it's too confusing. https://github.com/threefoldtech/tfchain_explorer/issues/196

**Comment by MohamedElmdary** [comment]
### Removed
#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/213

**Comment by mohamedamer453** [comment]
Verified on https://explorer.dev.grid.tf

Certification Type field was removed from the Farm Details

![image](https://user-images.githubusercontent.com/101194226/163185020-05991607-d279-4c02-bdbe-b43a0587bb12.png)
