### ISSUE TITLE
Statistics on explorerv3.grid.tf seem to be off 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#192]
Numbers seem to be way different than on explorer.threefold.io 
<img width="1382" alt="Screenshot 2022-03-28 at 18 14 11" src="https://user-images.githubusercontent.com/31733464/160441926-31ab3887-1738-4721-8136-db2ff68a7935.png">
<img width="1424" alt="Screenshot 2022-03-28 at 18 14 02" src="https://user-images.githubusercontent.com/31733464/160441930-c66ba31f-f81d-4035-bc13-900a7f174771.png">

**Comment by AhmedHanafy725** [comment]
The unified explorer on `explorer.threefold.io` is showing only the online nodes in the statistics view, but the grid3 explorer on `explorerv3.grid.tf` is showing all nodes(online + offline), so we need to make them work similarly 

@sabrinasadik @rkhamis  should we show online nodes only or all nodes on both? (in the statistics' view not the nodes' table)

**Comment by rkhamis** [comment]
i think we show the total number
then we should show number of online nodes as well


so we add a statistic showing online nodes while the old one shows the total number of nodes connected to the grid

**Comment by mohamedamer453** [comment]
Verified on https://explorer.dev.grid.tf/

The statistics page now shows online nodes only and the number in the statistics page matches the number of online nodes in the nodes table.

19 online nodes in the statistics page

![image](https://user-images.githubusercontent.com/101194226/163146036-44701d1b-dc7c-4881-822d-c5de26e44639.png)

Also 19 online nodes in the nodes table

![image](https://user-images.githubusercontent.com/101194226/163146149-25bb309a-bcde-4a6a-bf2d-8566365d9e87.png)

![image](https://user-images.githubusercontent.com/101194226/163146369-026ae664-8b74-4fcb-b898-094bf6787807.png)
