### ISSUE TITLE
Hide farm certification label

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_explorer#196]
A lot of users are telling us they have a Titan but it shows up as certified on the explorer. I thought the same thing but apparantly the node certification is correct, but farm certification is displayed as DIY. 
No need to show the farm certification for now, please hide.

**Comment by MohamedElmdary** [comment]
### Removed
#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/213

**Comment by mohamedamer453** [comment]
Verified on https://explorer.dev.grid.tf

Certification Type field was removed from the Farm Details

![image](https://user-images.githubusercontent.com/101194226/163185020-05991607-d279-4c02-bdbe-b43a0587bb12.png)
