### ISSUE TITLE
show node `interfaces` and `public-config`

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfchain_explorer#21]
Node object on tfchain has some other useful information that need to be shown on the explorer
- `interfaces`
- `public-config`

![image](https://user-images.githubusercontent.com/10920323/138676003-870d959d-0a1a-45d5-aa59-ca7212bfd474.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch `grid_updates`
### Commits
564b6794f27aa1d6ec4c0c1dcbf7d1b6265a05da
7337ddbc1164786cc821c0fc7250f5f7430ce302

**Comment by mhost39** [comment]
Verified
