### ISSUE TITLE
Updating toTeraOrGiga to handle PB

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfchain_explorer#22]
https://github.com/threefoldtech/grid_explorer_ui/blob/master/src/filters/toTeraOrGiga.ts

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`numbers_conversions`
#### Commit
73252699c0db1d56b3717d894d5468d3fca89815

![image](https://user-images.githubusercontent.com/46320202/139572803-fde0fb8f-eabf-4cb0-bc09-0b1879af861e.png)
![image](https://user-images.githubusercontent.com/46320202/139572975-fe7a5653-ba2d-47a8-ae72-06c0e6270c1e.png)
![image](https://user-images.githubusercontent.com/46320202/139572987-630d9e4a-c795-4f1e-bda4-bf5cdfc0d36d.png)
![image](https://user-images.githubusercontent.com/46320202/139572960-673e9876-177b-4791-adee-15607e5776ea.png)

**Comment by mhost39** [comment]
Verified
