### ISSUE TITLE
filter by country is missing

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfchain_explorer#24]
![Screenshot from 2021-10-28 13-16-49](https://user-images.githubusercontent.com/1689456/139257188-3335b6fb-1dc7-4c72-9d7a-02582d080aac.png)

**Comment by RafyAmgadBenjamin** [comment]
### verified 
### on testnet
https://explorer.test.grid.tf/nodes
### Branch
master
### tag
v3.0.0-rc10
