### ISSUE TITLE
filter by certification, pub ipaddr, min capacity,location available

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/tfchain_explorer#27]
needs to be easy to find nodes based on 

- certification status
- min capacity available (cu/su)
- location
- if there are pub ip addr available

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/140015334-e323fb69-453d-4531-9337-acb6f9c24c33.png)

this is not usable (need on country an continent level)

**Comment by rkhamis** [comment]
all done
