### ISSUE TITLE
put link to manual & complete manual

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/tfchain_explorer#29]
add to manual

- how to run this ourselves (info is already on home readme)
- link to up & running version for testnet & devnet

in readme
- link to manual wiki
- link to up & running version for testnet & devnet

**Comment by xmonader** [comment]
https://library.threefold.me/info/threefold#/manual_tfgrid3/threefold__grid3_explorer 
and installation instruction are in  the readme
