### ISSUE TITLE
Need to be able to see in the explorer if the farm has public IP space or not.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/tfchain_explorer#32]
I cannot determine in the explorer if a farm has public (IPv4 or IPv6) ipspace.  graphql gets me that information but I think it would be goo to have it in the epxlorer as well (attached to farm info).
![image](https://user-images.githubusercontent.com/13766992/140272701-a57fe9e0-754b-4857-a492-edef326881bf.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
grid_updates
### Commit ID
3dd34994f3b3409340ce77a03a820c177f3e3e0c

for checking if the farm has public IP we have added

- we have added `Public IPs` column
![image](https://user-images.githubusercontent.com/46320202/140747835-02ce6828-44e5-44a5-8375-94950cf008b1.png)

- we have added public ips filter so you can filter the farms with the number of public ips
![image](https://user-images.githubusercontent.com/46320202/140747921-11fbeb26-670c-4386-a56d-8815d548e663.png)

**Comment by mhost39** [comment]
Verified 
branch: master 
commit: 3dd3499
