### ISSUE TITLE
remove grid version from UI

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#39]
![image](https://user-images.githubusercontent.com/64129/140402198-da1b4e2f-dd21-4dd8-896c-b4f5b656b3c2.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`grid_updates`

### Commit ID
eeb779462841c664a58dc3822cfa949dbdc57e1d

![image](https://user-images.githubusercontent.com/46320202/140746679-9f3547fb-0988-47fc-9710-17bcd2186068.png)

**Comment by mhost39** [comment]
Verified 
branch: mater
commit: eeb779462841c664a58dc3822cfa949dbdc57e1d
