### ISSUE TITLE
Show nodes with  gateways only ->  Gateways 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#40]
![image](https://user-images.githubusercontent.com/64129/140402410-93c2ab32-81cc-4d33-86d5-4bf05f77b12e.png)
change the wording please

**Comment by RafyAmgadBenjamin** [comment]
## Done
## Branch
`grid_updates`
## Commit ID
c542ac72eaff30d74bc786d6f11ef6badd85386a

![image](https://user-images.githubusercontent.com/46320202/140746402-939b6c55-120a-403b-a690-a5e92b44c7c6.png)

**Comment by mhost39** [comment]
Verified 
commit: c542ac72eaff30d74bc786d6f11ef6badd85386a
branch: master
