### ISSUE TITLE
Error in building the image

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#43]
couldn't build the image 
![image](https://user-images.githubusercontent.com/46320202/140754652-e718979d-791f-4439-b4b2-1d3600a12b52.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`grid_updates`
### Commit
9f36949fce7042abe7be59d8a3c337b2ba3a677b

![image](https://user-images.githubusercontent.com/46320202/140755417-218f4160-4611-4908-959c-1841db42d656.png)

**Comment by mhost39** [comment]
Verified
branch: master
commit: 9446898821f59a0c80ec07e77d1708452001a68e
![image](https://user-images.githubusercontent.com/31102305/144057947-bf08709a-4725-4d1b-ba78-8e67b672c30f.png)
