### ISSUE TITLE
Add no of validators to explorer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#44]
can be retrieved from 
![image](https://user-images.githubusercontent.com/64129/140808050-fc75ed9a-c080-4082-b887-9de3b04be45c.png)

**Comment by RafyAmgadBenjamin** [comment]
I can't find this information in graphql endpoints

**Comment by RafyAmgadBenjamin** [comment]
I have discussed this with @DylanVerstraete  and we reached that we can't get the validators from graphql as it is not indexed there.

**Comment by xmonader** [comment]
I'ts ok not needed at all now
