### ISSUE TITLE
Give more human readable names  for our filters

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#50]
![image](https://user-images.githubusercontent.com/46320202/141113959-932357bd-d846-41c5-af7f-a112822c3adc.png)

##### example
`countryfullname` filter

**Comment by mhost39** [comment]
Verified
branch: master
![image](https://user-images.githubusercontent.com/31102305/144057211-9fb7ef30-ba38-49f8-bf59-e81dc1403f73.png)
