### ISSUE TITLE
incorrect contracts number

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#53]
![image](https://user-images.githubusercontent.com/64129/141375025-94364a83-9c02-41d1-a223-dbf4ab26c073.png)
while in the explorer it says 
![image](https://user-images.githubusercontent.com/64129/141375071-98c77c9d-e37d-4d6b-9c94-126742d429f2.png)

**Comment by MohamedElmdary** [comment]
## Fixed

### PR
https://github.com/threefoldtech/tfchain_explorer/pull/54
