### ISSUE TITLE
Incorrect number of countries

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/tfchain_explorer#55]
In explorer countries mentioned is 250. This can’t be right, I suspect the table is consilted with all possible countries, not the number of unique countries where nodes are running.

**Comment by xmonader** [comment]
Good catch

![image](https://user-images.githubusercontent.com/64129/141954475-c5fbc6d8-c4b0-43cf-9ffa-62fdbb27b82e.png)
@RafyAmgadBenjamin please check

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`fix_countries`
### Commit
71d8de7013e456b79c72c995071ff38f26809e64

![image](https://user-images.githubusercontent.com/46320202/141965274-018a1148-7cc6-4f39-a2ac-3bb2dd97f803.png)



but there is another issue related to the data inconsistency in graphql 
![image](https://user-images.githubusercontent.com/46320202/141965383-280b1688-d538-4a59-a1e5-898b8e6c96d0.png)

**Comment by mhost39** [comment]
Verified 
commit: 71d8de7013e456b79c72c995071ff38f26809e64
branch: master
