### ISSUE TITLE
node public config doesn't show the 'domain'

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#56]
![image](https://user-images.githubusercontent.com/46320202/141960830-57d1e39f-de1b-4204-a0b7-af83a10bc4e6.png)
![image](https://user-images.githubusercontent.com/46320202/141960835-38a80c2c-ca01-4f6c-81b9-a5578bd3073d.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
`nodes_updates`
### Commit
eb02cab0f4e5192ea4596da3b2e1bb843b06cb4c

![image](https://user-images.githubusercontent.com/46320202/141983314-7f575981-8e45-4127-8775-b7fa6b9c6d33.png)

**Comment by mhost39** [comment]
Verified 
branch: master 
commit: eb02cab0f4e5192ea4596da3b2e1bb843b06cb4c
