### ISSUE TITLE
can't select the nodes to deploy on due to lack of information 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#57]
### example:
Node should display 
used CRU / total CRU

The query to the node (via the cache service) will also indicate if the node is responsive (UP) or not

**Comment by RafyAmgadBenjamin** [comment]
the used resources piece of information is found in the `grid proxy` and not found in the graphql, so shall we update the graphql to expose this data or shall we use the `grid proxy` to get this information.
@xmonader 

`grid proxy`
![image](https://user-images.githubusercontent.com/46320202/141991179-36e6ccfb-e350-4c74-8493-c75fbac5668a.png)

----

`graphql`
![image](https://user-images.githubusercontent.com/46320202/141991295-388ef605-cf4b-47a9-a8bb-6d816fee248f.png)

**Comment by xmonader** [comment]
You need to use the grid proxy not the graphql for the used resources

**Comment by RafyAmgadBenjamin** [comment]
while trying to get the data from tfgrid proxy i found the CORS policy is blocked 
![image](https://user-images.githubusercontent.com/46320202/142010389-683a4774-ee01-4383-9bd5-4b702b05a15e.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
`nodes_uodates`
### Commit
38759dfdfd0b03de740a3fc6b964625576e4aae2

![image](https://user-images.githubusercontent.com/46320202/142222125-4a9883cc-d0a1-451a-b5dd-0c62dd3b08a7.png)

**Comment by mhost39** [comment]
Verified 
branch: master
commit: 38759dfdfd0b03de740a3fc6b964625576e4aae2
