### ISSUE TITLE
update search scales

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#61]
HRU till 300 TB
MRU till 10 TB
CRU till 60
SRU till 10 TB

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`range_filters`
### Commit
0232dac046ae2f3a831bbe40726ca4ed8ca29149
![image](https://user-images.githubusercontent.com/46320202/142759062-a7e91dcc-34d4-423e-a168-2225b35327f8.png)

**Comment by mhost39** [comment]
Verified
commit: 0232dac046ae2f3a831bbe40726ca4ed8ca29149
branch: master
![image](https://user-images.githubusercontent.com/31102305/144053447-cb76be51-9d32-4595-8bc2-ba880482aa46.png)
