### ISSUE TITLE
sort node details elements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#63]
![image](https://user-images.githubusercontent.com/64129/142768434-10e5f092-ba70-4ec8-a8c2-12b75b372564.png)

should have the node used resources in the very beginning and everything else after

node details, farm details, interface details, twin, country, location

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
`node_updates`
### commit 
dbda12aff6cec6e4f8be5860205bfd571f1facba
![image](https://user-images.githubusercontent.com/46320202/142839607-04c4beb3-d204-4f70-88a5-d8ebb157aea0.png)

**Comment by mhost39** [comment]
Verified 
commit: dbda12aff6cec6e4f8be5860205bfd571f1facba
branch: master
