### ISSUE TITLE
Don't put packaged chart binaries in the source

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfchain_explorer#64]
Please do not put packaged charts (binary tgz’s) in the git sources. If you want to distribute a packaged chart, create a release and add it to the release, not in the git sources

I see you already created a release with release notes, fantastic

so add the packaged chart to the release and remove it from the git sources please

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
master
### Commit 
2299419ee2344517f296f834e8f48d9556fd9050

I have removed the .tar files from the master branch and i see them already added to the release note and I will keep following this convention in the next releases
