### ISSUE TITLE
Country location sometimes doesn't appear on the map in node details section 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#65]
![image](https://user-images.githubusercontent.com/46320202/142837286-e49b4eae-c7c8-415b-8f4b-f961b98c6708.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch 
`node_updates`
### Commit
84325e6da95df7b7bab073b68fb5782ccd592186
![image](https://user-images.githubusercontent.com/46320202/142837659-62955729-d5b0-41f6-b0ba-f2c9c8091acd.png)

**Comment by mhost39** [comment]
Verified
commit: 84325e6da95df7b7bab073b68fb5782ccd592186
branch: master
![image](https://user-images.githubusercontent.com/31102305/144051635-63895382-79f5-4229-86e4-6ed5b44d6ce3.png)
