### ISSUE TITLE
country flag sometimes not render 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#66]
![image](https://user-images.githubusercontent.com/46320202/142845814-1ccfee22-fe33-4fc2-84d0-026cdcadbec9.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`node_updates`
### Commit
04cac1c2e5fce0743bd01e5bb75f916dd2b9c141


![image](https://user-images.githubusercontent.com/46320202/142847034-9ad6aeea-1ab0-4e1f-b0c5-1ff166f5c14e.png)

**Comment by mhost39** [comment]
Verified
commit: 04cac1c2e5fce0743bd01e5bb75f916dd2b9c141
branch: master 
![image](https://user-images.githubusercontent.com/31102305/144050898-4a2f9da9-185d-4880-9fd9-614e78a867a9.png)
