### ISSUE TITLE
shouldn't display NaN in case that the resource if full 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#68]
In case the resource is full shouldn't display NaN and should display 100%

![image](https://user-images.githubusercontent.com/46320202/143224613-f2e23aff-9de2-4039-bb60-6096b5c9e706.png)

**Comment by RafyAmgadBenjamin** [comment]
after investigation, found that actually, the node doesn't have HRU it is zero 
![image](https://user-images.githubusercontent.com/46320202/143228292-589d9e40-213b-4a96-9535-450d2ecb04ee.png)

so shall we
-  remove HRU circle
 or
-  make it 100% full in this case (but this could be misleading)

**Comment by RafyAmgadBenjamin** [comment]
I will go for removing the resource circle in case it is zero

**Comment by RafyAmgadBenjamin** [comment]
After discussions, we will go for the second approach as it is more meaningful 
`make the circle is 100% full `

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`fix_issues`
### Commit
778f85fee3207d1e1262a949db1fac0dd236650c

**Comment by mhost39** [comment]
Verified 
commit: 778f85fee3207d1e1262a949db1fac0dd236650c
branch: master
