### ISSUE TITLE
read farming policies github

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#70]
https://github.com/threefoldtech/tfchain/issues/105

instead of weird numbers we are showing

**Comment by RafyAmgadBenjamin** [comment]
in progress on branch 
`master_farming_policy`
- we have modified the code to get the data from the json file
- injected code into the actions so it happened one time in during initialization of the app
- we got error on binding still need more investigation

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch
`master_farming_Policy`
### Commit
f7c015c652b65e8f3df2eb8f8968cf3d3ad31f58

![image](https://user-images.githubusercontent.com/46320202/144006723-754f4860-a36b-4962-8e71-110926e516c3.png)

**Comment by mhost39** [comment]
Verified 
commit: f7c015c652b65e8f3df2eb8f8968cf3d3ad31f58
branch: master
