### ISSUE TITLE
show offline nodes option

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#71]
the listed nodes in the UI should be the "online" ones by default. 

let's add a toggle to include offline nodes in the listing.

**Comment by RafyAmgadBenjamin** [comment]
we used to filter the online nodes depending on the uptime reported from graphql 
```json
data": {
    "nodes": [
      {
        "nodeId": 42,
        "uptime": 292686,
        "id": "GE2JV-y_xq"
      },
      {
        "nodeId": 8,
        "uptime": 879961,
        "id": "RISyQGJcEOD"
      },
      {
        "nodeId": 23,
        "uptime": 413,
        "id": "NjclxcOGPq"
      },
      {
        "nodeId": 37,
        "uptime": 299898,
        "id": "hQjn_32TzN"
      },
      {
        "nodeId": 26,
        "uptime": 326908,
        "id": "oGFPjt_8tr"
      },
      {
        "nodeId": 43,
        "uptime": 292095,
        "id": "yOlxqj3v-W"
      },
      {
```

but this is not really accurate

so now to make it work in the correct way we have to depend on the `gridproxy` instead of `graphql`

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_nodes_status`

![image](https://user-images.githubusercontent.com/46320202/144742326-5fb5cd07-04d8-4822-aef3-80c51b17ae7f.png)
![image](https://user-images.githubusercontent.com/46320202/144742328-776bd5e2-091e-4c7a-8527-c6b883787a9d.png)

**Comment by RafyAmgadBenjamin** [comment]
### verified 
### on testnet
https://explorer.test.grid.tf/nodes
### Branch
master
### tag
v3.0.0-rc10

![image](https://user-images.githubusercontent.com/46320202/145956234-ce5f62eb-2f9e-400f-aa56-9fd1758f2702.png)
![image](https://user-images.githubusercontent.com/46320202/145956259-d2e6d19b-9675-4a78-a9ac-60d666afbf09.png)
![image](https://user-images.githubusercontent.com/46320202/145956283-17649439-975d-4c9c-a8e3-fb3b1ff60989.png)
