### ISSUE TITLE
handle details view of down nodes

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_explorer#72]
![image](https://user-images.githubusercontent.com/64129/143540629-34a4afce-39b5-4dbf-888b-19ef6fa78fc5.png)

Should show something like `Node is offline`, total used should be 0, and show all the nodes resources

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_nodes_status`

![image](https://user-images.githubusercontent.com/46320202/144742326-5fb5cd07-04d8-4822-aef3-80c51b17ae7f.png)
![image](https://user-images.githubusercontent.com/46320202/144742328-776bd5e2-091e-4c7a-8527-c6b883787a9d.png)

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_node_resources_status`

![image](https://user-images.githubusercontent.com/46320202/144743813-74f8f344-0cbc-4903-be5f-31d1fc919367.png)
![image](https://user-images.githubusercontent.com/46320202/144743816-97b88a85-61a1-4ed4-8488-cff53e2679d6.png)


### PR
https://github.com/threefoldtech/tfchain_explorer/pull/82

**Comment by RafyAmgadBenjamin** [comment]
### verified 
### on testnet
https://explorer.test.grid.tf/nodes
### Branch
master
### tag
v3.0.0-rc10

![image](https://user-images.githubusercontent.com/46320202/145956680-98b74032-7f1a-48d8-a5df-f640c69986aa.png)
![image](https://user-images.githubusercontent.com/46320202/145956753-b5e5255d-73da-4c77-90f4-f4623a406515.png)
