### ISSUE TITLE
Better ui for statistics

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfchain_explorer#74]
### Updates
add a better ui
![image](https://user-images.githubusercontent.com/31689104/143832511-d1c9202b-ae17-4276-9370-e32ee148483f.png)

**Comment by xmonader** [comment]
Can we remove the page leading text "statistics"

**Comment by MohamedElmdary** [comment]
Updated @xmonader

**Comment by mhost39** [comment]
Verified 
commit: bab7db1c11883175dd1062659801492c8ab3df16
branch: master
![image](https://user-images.githubusercontent.com/31102305/144046628-0803ba20-2f13-4061-bd13-8ca6dbed13a7.png)
