### ISSUE TITLE
statistics page show default data tell the graphql respond

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#76]
statistics page shows default data tell we got the data from graphql 
![image](https://user-images.githubusercontent.com/46320202/143860647-cf68da5d-3356-472c-a579-5e975a5fc98c.png)

I suggest adding a loader tell we got the data then displaying it

**Comment by mhost39** [comment]
Verified 
commit: 922206f8f8d5245127d1e7699894594f81ee69b8
branch: master
