### ISSUE TITLE
filtered results in portal not reflected on the map

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfchain_explorer#79]
in portal if we for example filtered by country to be Egypt, the map still showing nodes in other countries and the same issue is applied to all filter
![Screenshot from 2021-11-15 17-07-43](https://user-images.githubusercontent.com/1689456/141805161-2678ab51-de24-40ec-9e87-10785c4dfe96.png)
s

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_fix_issues,`
### Commit
eea844435b835f2ce3b489fbab03a28c42e8e4ee

![image](https://user-images.githubusercontent.com/46320202/146164986-c0378262-a0c7-482f-a8e3-4548d5768c54.png)

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`

![image](https://user-images.githubusercontent.com/46320202/147671358-defbbd46-df07-48c3-9930-77cfa993ccb4.png)
![image](https://user-images.githubusercontent.com/46320202/147671425-7c415e47-7eb4-4fb7-9b80-1aadbc95af4b.png)
