### ISSUE TITLE
Filtering using the slider has usability issues

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfchain_explorer#80]
The current sliders for filtering nodes has some usability issues

1. the unit that we filter with is not visible to the user if it is in Megabytes or Gigiabytes
2. the text box that has the max value is too small for the default value `9007199254740991` shown as `900`
3. the default values is like out of scale for the current nodes for example the largest node MRU is 270 while the max value is `9007199254740991` so to really use the filter the user needs to move the slider for 0.1 pixel or so to filter on the above results should be relative to the largest node somehow be 270 or 300 for example
![Screenshot from 2021-11-15 17-27-41](https://user-images.githubusercontent.com/1689456/141808969-dc873274-f4c7-48ed-af1c-f90e8ffff1c5.png)

**Comment by xmonader** [comment]
done in #62
