### ISSUE TITLE
Use proxy url based on network

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfchain_explorer#83]
current explorer using only `dev` network we need to add a configuration that using `dev | test` based on network

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
`master_proxy_networks`
### PR
https://github.com/threefoldtech/tfchain_explorer/pull/84

**Comment by RafyAmgadBenjamin** [comment]
### verified 
### on testnet
https://explorer.test.grid.tf/nodes
### Branch
master
### tag
v3.0.0-rc10
