### ISSUE TITLE
change vue favicon to Threefold favicon 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfchain_explorer#86]
this should be changed ASAP as we are going to announce about explorer and admin portal today on our main site in two new blogs

![Screenshot from 2021-12-08 09-17-34](https://user-images.githubusercontent.com/26298009/145165259-88440108-9224-4ce9-9af5-e7d40e89f675.png)

**Comment by ehab-hassan** [comment]
![favicon](https://user-images.githubusercontent.com/10484295/145174643-33748a02-4c8c-4417-b91a-35d6050f5a2c.png)
![favicon_white](https://user-images.githubusercontent.com/10484295/145174646-b60b207f-9155-409e-8249-74e495e28431.png)

**Comment by MohamedElmdary** [comment]
### Updated

#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/87

**Comment by hossnys** [comment]
threefold favicon is not showing after deploying the latest version of tfchain-explorer on devnet

![Screenshot from 2021-12-12 11-13-12](https://user-images.githubusercontent.com/26298009/145707020-d36664dc-2d54-4307-9086-dd9895b4fe70.png)

![Screenshot from 2021-12-12 11-23-50](https://user-images.githubusercontent.com/26298009/145707052-54d8c32f-0bc7-47e8-9a96-1b6984f6e570.png)

**Comment by MohamedElmdary** [comment]
After double check the favicon
seems like the deployed version doesn't use the latest build
please make sure to pull latest changes and re-build

**Comment by hossnys** [comment]
verified with @RafyAmgadBenjamin  , the latest image was uploaded only to the master node of K8s cluster but after uploading it to worker nodes all become fine
