### ISSUE TITLE
Slider filters do not have visible values

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_explorer#98]
The order of Node Twin IDs is sorted arbitrarily so it is confusing for the end-user since the nodes are using INT ID.
![image](https://user-images.githubusercontent.com/46320202/145973472-4cd59daf-c749-47c8-a069-e63bbd837025.png)

**Comment by xmonader** [comment]
I think the description of the original issue is wrong https://circles.threefold.me/project/test-tfgrid3/issue/47

**Comment by RafyAmgadBenjamin** [comment]
I think what he meant was that he can't see the value (digits) in the filter

**Comment by RafyAmgadBenjamin** [comment]
### Done
### Branch
```master_fix_issues```
### Commit 
55ed425db84f15e2e957484cbe6055d7d7d811ba
![image](https://user-images.githubusercontent.com/46320202/146190242-b1a5f690-84d7-44d9-b954-217baddbc91d.png)

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`master`
### Tag
`v3.0.0-rc14`

![image](https://user-images.githubusercontent.com/46320202/147671144-ac4f3bc3-a599-4f29-a89e-2441cc34bb72.png)
